version: '3.8'

services:
  backend:
    build: ./backend
    container_name: mi-backend
    ports:
      - "3000:3000"
    networks:
      - app-net

  frontend:
    build: ./frontend
    container_name: mi-frontend
    ports:
      - "8081:80"
    depends_on:
      - backend
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
